### ISSUE TITLE
feat: Benchmarking environment and hyper parameters.

### ISSUE THREAD

**Issue by hmasum52** [roboflow/model-leaderboard#28]
Hi @LinasKo and @onuralpszr , for creating this leaderboard. This leaderboard this really helpful for model selection.

I think you should mention what environment is used and what hyperparameters are used in website.

Here are some possible information:
- Python version
- machine used to validate
- confidence threshold
- batch size etc.

**Comment by LinasKo** [comment]
Excellent point!

In fact, that's what we were planning next, but more focused on parameters such as confidence and IoU threshold.

Until we start benchmarking the memory & speed, we found the results were almost identical on any machine we tested (5th digit difference between GPU and CPU runs).

**Comment by onuralpszr** [comment]
@hmasum52  I just finished adding run parameters and showed in website so I am closing this as complete :) Feel free to re-open or open issue 👋   

Completed via : #31
